title:            Let's help each other
description:      Share stuff with friends. Help others with usefull stuff.
logo:             //s3-eu-west-1.amazonaws.com/assets.jipio.com/beta/assets/img/favicon.ico
assets:           //s3-eu-west-1.amazonaws.com/assets.jipio.com/corporate/
disqus_shortname:
#Comment out url when working locally to resolve base urls correctly
url: http://jipio.com
domain: jipio.com

# Owner/author information
owner:
  name: Jipio
  avatar: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash3/t1/c35.35.441.441/s320x320/577975_170520776430896_314304979_n.png
  email: hello@jipio.com

# Analytics and webmaster tools stuff goes here
google_analytics: UA-28530539-3

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Blog
    url: /articles
  - title: Code
    url:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:
future:      true
pygments:    true
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

activate: syntax
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]
